### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION

### ISSUE THREAD

**Issue by nitinagr** [sacOO7/socketcluster-client-java#19]
My connection with SC getting disconnected sometimes and when i try to send some msg app crashes with below error can you please help me here.

shutting down VM
11–13 09:20:56.221 3371–3371/git.cluster.io.socketclusterandroid E/AndroidRuntime: FATAL EXCEPTION: main
 Process: git.cluster.io.socketclusterandroid, PID: 3371
 java.lang.NullPointerException: Attempt to invoke virtual method ‘void io.github.sac.Socket$Channel.publish(java.lang.Object)’ on a null object reference
 at git.cluster.io.socketclusterandroid.MainActivity$5.onClick(MainActivity.java:146)
 at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
 at android.os.Handler.dispatchMessage(Handler.java:102)
 at android.os.Looper.loop(Looper.java:154)
 at android.app.Act

**Comment by sacOO7** [comment]
Hey please make sure you are creating channel first and then publish on it.

**Comment by nitinagr** [comment]
That i am doing but when the connection is broken this exception crash the app.There should be a way to catch this exception and handle gracefully.

**Comment by sacOO7** [comment]
I think that shouldn't create a problem. I'm sure of that. Can you check if channel object become null after connection is broken.

**Comment by sacOO7** [comment]
Hi @nitinagr is your problem got solved? If it is let me know, I am closing this issue soon

**Comment by nitinagr** [comment]
Yes resolved.Please close it.

**Comment by amy6** [comment]
Hey @nitinagr, I am facing the same problem and was wondering if you could tell me what the fix was in your case?
